package com.springsecurity.security.event;

import lombok.extern.slf4j.Slf4j;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.context.event.EventListener;
import org.springframework.security.authentication.event.AbstractAuthenticationFailureEvent;
import org.springframework.security.authentication.event.AuthenticationSuccessEvent;
import org.springframework.stereotype.Component;

@Component
@Slf4j
public class AuthenticationEvent {

//    Below line will be generated by lombok if we use @Slf4j
//    private static final Logger log = LoggerFactory.getLogger(AuthenticationEvent.class);

    @EventListener
    public void onSuccess(AuthenticationSuccessEvent successEvent){
        log.info("Login success for user : {}", successEvent.getAuthentication().getName());
    }

    @EventListener
    public void onFailure(AbstractAuthenticationFailureEvent failureEvent){
        log.error("Login failed for user: {} due to: {}", failureEvent.getAuthentication().getName(), failureEvent.getException().getMessage());
    }
}
